// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlc

import ()

type Customer struct {
	ID        int32
	FirstName string
	LastName  string
	Email     string
	Phone     string
}
