development:
  dialect: postgres
  datasource: host=${PSQL_HOST} port=${PSQL_PORT} dbname=${PSQL_DB} user=${PSQL_USER} password=${PSQL_PASSWORD} sslmode=${PSQL_SSLMODE}
  dir: sql/migrations
  table: migrations